### ISSUE TITLE
Homepage: General issues (First pass)

### ISSUE THREAD

**Issue by luxumbra** [marleymarl/geotimeline-website#11]
#### Mobile:
- [x] 1. The whole hero / CTA component needs to be wider on mobile so it fits on the screen
- [ ] 2. Steps need more work on styles and content. (There is no design for these)
- [x] 3. The logo / brand text is broken on mobile.
- [ ] 4. FAQ comp is too narrow on mobile.
- [ ] 5. Carousel needs sorting on mobile. Too narrow / whitespace issue
- [ ] 6. General responsiveness needs attention (whitespace, font size, etc)

#### Desktop
- [ ] 1. Same as number 2 above
- [ ] 2. The scroll-to-content icon isn't linked
- [ ] 3. General font size tweaks - up the font size a bit for body text

#### General page improvements and notes
Other enhancements welcome but I think tackling the Mobile then Desktop specific issues is priority.

**Comment by V1shvesh** [comment]
Picking up Mobile issues 1-4.
